"""
Django settings for coursereviews project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z7@_yq*kmgukv8*&at_glyx@08zic3o(*4(gxfvw9%fbgl(e-('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_daraja',
    'courses',
    'blog',
    'students',
     'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coursereviews.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 👇 This tells Django to look in the global "templates" folder
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coursereviews.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

import dj_database_url
import os

# --- STATIC FILES (WhiteNoise) ---
STATIC_URL = '/static/'
# This is where files go when you run collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# This compresses files to make your site faster
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- DATABASE CONFIGURATION ---
# This automatically switches between SQLite (Local) and PostgreSQL (Render)
DATABASES = {
    'default': dj_database_url.config(
        # Fallback to SQLite if we are on your laptop
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}

# --- SECURITY ---
# Allow the website to run on Render's URL
ALLOWED_HOSTS = ['*']  # For testing. Ideally, put your Render URL here later.

import os

# The URL the browser uses (e.g., http://site.com/media/image.jpg)
MEDIA_URL = '/media/'

# The folder on your computer where files are saved
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'students:enter_grades'
LOGOUT_REDIRECT_URL = 'home'

# --- M-PESA CONFIGURATION (SANDBOX) ---
MPESA_ENVIRONMENT = 'sandbox' # Change to 'production' when live
MPESA_CONSUMER_KEY = 'pSPc69gLJKIso3HbAHjqbJH7fAppxDYHkp6VDlXbO2AuRuUg'     # <--- Get this from Safaricom Portal
MPESA_CONSUMER_SECRET = 'kF8dLmfqiG9A8GwbDsrgEdfYjrK0KGhBvhqwvmKvEIHV52iJGREWDd1b0UHWPQa9' # <--- Get this from Safaricom Portal
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919' # Standard Sandbox Passkey
MPESA_SHORTCODE = '174379' # Standard Sandbox Shortcode
MPESA_EXPRESS_SHORTCODE = '174379'
MPESA_TYPE = 'CustomerPayBillOnline'