# Generated by Django 5.2.7 on 2025-11-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='kcse_mean_grade',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='subjects',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='cluster_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade1',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade2',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade3',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade4',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade5',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade6',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade7',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='mean_grade',
            field=models.CharField(default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='name',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='subject1',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='subject2',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='subject3',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='subject4',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='subject5',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='subject6',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='subject7',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], default='A', max_length=10),
            preserve_default=False,
        ),
    ]
