# Generated by Django 5.2.7 on 2025-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentgrade_kcse_mean_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='name',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='full_name',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject1',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject2',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject3',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject4',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject5',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject6',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject7',
            field=models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('kis', 'Kiswahili'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('hist', 'History'), ('geo', 'Geography'), ('cre', 'CRE'), ('bus', 'Business')], max_length=20),
        ),
    ]
