# Generated by Django 5.2.7 on 2025-11-09 14:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('students', '0003_remove_studentgrade_name_studentgrade_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_paid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mathematics', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('english', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('kiswahili', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('biology', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('physics', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('chemistry', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('history', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('geography', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('cre', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ire', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('hre', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('business_studies', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('agriculture', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('computer_studies', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('music', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('art_and_design', models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('cluster_points_medicine', models.FloatField(default=0.0)),
                ('cluster_points_engineering', models.FloatField(default=0.0)),
                ('cluster_points_law', models.FloatField(default=0.0)),
                ('cluster_points_arts', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentGrade',
        ),
    ]
