# Generated by Django 5.2.7 on 2025-11-09 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_payment_studentgrades_delete_studentgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrades',
            name='arabic',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='aviation_technology',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='building_construction',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='drawing_and_design',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='electricity',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='french',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='german',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='home_science',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='kenyan_sign_language',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='metalwork',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='power_mechanics',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='woodwork',
            field=models.IntegerField(blank=True, choices=[(12, 'A'), (11, 'A-'), (10, 'B+'), (9, 'B'), (8, 'B-'), (7, 'C+'), (6, 'C'), (5, 'C-'), (4, 'D+'), (3, 'D'), (2, 'D-'), (1, 'E')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
