# Generated by Django 5.2.7 on 2025-11-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentgrades_arabic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrades',
            name='overall_points',
            field=models.FloatField(default=0.0),
        ),
    ]
