# Generated by Django 5.2.7 on 2025-11-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentgrades_overall_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrades',
            name='overall_points',
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='mean_grade',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], help_text='Your official KCSE Mean Grade', max_length=2, null=True),
        ),
    ]
