# Generated by Django 5.2.7 on 2026-01-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(blank=True, help_text='M-Pesa Transaction Code', max_length=20, null=True),
        ),
    ]
