# Generated by Django 5.2.7 on 2026-01-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_payment_date_paid_payment_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrades',
            name='edit_count',
            field=models.IntegerField(default=0, help_text='Number of times grades have been edited after payment'),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
