# Generated by Django 5.2.7 on 2025-11-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('bachelors', 'Bachelor Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('artisan', 'Artisan')], max_length=20)),
                ('path', models.CharField(choices=[('medicine', 'Medicine & Health Sciences'), ('engineering', 'Engineering & Technology'), ('business', 'Business & Economics'), ('ict', 'Information Technology'), ('education', 'Education'), ('agriculture', 'Agriculture & Environment'), ('arts', 'Arts, Media & Humanities'), ('law', 'Law & Criminology'), ('hospitality', 'Hospitality & Tourism'), ('science', 'Pure & Applied Sciences'), ('others', 'General & Social Studies')], max_length=50)),
                ('min_grade', models.CharField(max_length=2)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
