# Generated by Django 5.2.7 on 2025-11-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='min_grade',
        ),
        migrations.AddField(
            model_name='course',
            name='career_path_info',
            field=models.TextField(blank=True, help_text='Example career path after this course', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='min_cluster_points',
            field=models.FloatField(blank=True, default=0.0, help_text='Minimum cluster points (if applicable, e.g., for degrees)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='min_mean_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E'), ('Any', 'Any')], default='Any', help_text='Minimum KCSE Mean Grade required.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_requirements',
            field=models.TextField(blank=True, help_text="Specific subject requirements, e.g., 'C+ in Maths'", null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Artisan', 'Artisan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='path',
            field=models.CharField(choices=[('Medicine', 'Medicine & Health Sciences'), ('Engineering', 'Engineering & Technology'), ('Business', 'Business & Economics'), ('ICT', 'Information Technology'), ('Education', 'Education'), ('Agriculture', 'Agriculture & Environment'), ('Arts', 'Arts, Media & Humanities'), ('Law', 'Law & Criminology'), ('Hospitality', 'Hospitality & Tourism'), ('Science', 'Pure & Applied Sciences'), ('Others', 'General & Social Studies')], max_length=50),
        ),
    ]
